import type { Policy, PolicyException } from '../shared/types';

export const MOCK_POLICIES: Policy[] = [
  { id: 'pol-001', key: 'skill.req-to-user-story.aut', name: 'req-to-user-story autonomy', category: 'autonomy', scopeType: 'platform', scopeId: '*', boundTo: 'req-to-user-story', version: 1, status: 'active', body: { defaultLevel: 'L1-Assist', escalation: 'PLATFORM_ADMIN' }, createdAt: '2026-03-01T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-002', key: 'skill.incident-diagnosis.aut', name: 'incident-diagnosis autonomy', category: 'autonomy', scopeType: 'platform', scopeId: '*', boundTo: 'incident-diagnosis', version: 2, status: 'active', body: { defaultLevel: 'L2-Auto-with-approval' }, createdAt: '2026-03-05T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-003', key: 'deploy.approval-required', name: 'Deploy Approval Required', category: 'approval', scopeType: 'platform', scopeId: '*', boundTo: null, version: 1, status: 'active', body: { requireApproval: true, approverRoles: ['WORKSPACE_ADMIN'] }, createdAt: '2026-03-10T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-004', key: 'risk.blast-radius-limit', name: 'Blast Radius Limit', category: 'risk-threshold', scopeType: 'platform', scopeId: '*', boundTo: null, version: 1, status: 'active', body: { maxBlastRadius: 'namespace', maxRevenueImpactUsd: 5000 }, createdAt: '2026-03-12T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-005', key: 'action.restart-gated', name: 'Restart Service Gate', category: 'action', scopeType: 'platform', scopeId: '*', boundTo: 'incident-remediation', version: 1, status: 'active', body: { requireApproval: true }, createdAt: '2026-03-15T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-006', key: 'skill.code-review.aut', name: 'code-review-assist autonomy', category: 'autonomy', scopeType: 'platform', scopeId: '*', boundTo: 'code-review-assist', version: 1, status: 'draft', body: { defaultLevel: 'L0-Manual' }, createdAt: '2026-04-01T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-007', key: 'deploy.canary-threshold', name: 'Canary Deployment Threshold', category: 'risk-threshold', scopeType: 'platform', scopeId: '*', boundTo: null, version: 1, status: 'inactive', body: { errorRateMax: 0.01 }, createdAt: '2026-04-05T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-008', key: 'exception.weekend-hotfix', name: 'Weekend Hotfix Exception', category: 'exception', scopeType: 'workspace', scopeId: 'ws-default', boundTo: null, version: 1, status: 'active', body: { allowBypass: true }, createdAt: '2026-04-10T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-009', key: 'approval.pr-merge', name: 'PR Merge Approval', category: 'approval', scopeType: 'platform', scopeId: '*', boundTo: null, version: 1, status: 'active', body: { minReviewers: 2 }, createdAt: '2026-04-12T10:00:00Z', createdBy: 'admin@sdlctower.local' },
  { id: 'pol-010', key: 'action.scale-resources', name: 'Scale Resources Gate', category: 'action', scopeType: 'platform', scopeId: '*', boundTo: 'incident-remediation', version: 1, status: 'active', body: { requireApproval: true, maxReplicas: 10 }, createdAt: '2026-04-14T10:00:00Z', createdBy: 'admin@sdlctower.local' },
];

export const MOCK_POLICY_EXCEPTIONS: PolicyException[] = [
  { id: 'pex-001', policyId: 'pol-003', reason: 'Weekend hotfix exception for critical production fix', requesterId: 'bob@corp.example', approverId: 'admin@sdlctower.local', createdAt: '2026-04-16T14:00:00Z', expiresAt: '2026-05-01T00:00:00Z', revokedAt: null },
  { id: 'pex-002', policyId: 'pol-005', reason: 'Emergency restart during P0 incident INC-0422', requesterId: 'carol@corp.example', approverId: 'admin@sdlctower.local', createdAt: '2026-04-17T14:05:00Z', expiresAt: '2026-04-18T14:05:00Z', revokedAt: null },
  { id: 'pex-003', policyId: 'pol-004', reason: 'Namespace-scoped test for canary rollout', requesterId: 'dave@corp.example', approverId: 'alice@corp.example', createdAt: '2026-04-15T10:00:00Z', expiresAt: '2026-04-16T10:00:00Z', revokedAt: null },
  { id: 'pex-004', policyId: 'pol-001', reason: 'Expired: demo exception for sprint review', requesterId: 'frank@corp.example', approverId: 'admin@sdlctower.local', createdAt: '2026-03-28T10:00:00Z', expiresAt: '2026-03-29T10:00:00Z', revokedAt: null },
];
