import type { PipelineProfile } from '../types/requirement';

export const IBM_I_PROFILE: PipelineProfile = {
  id: 'ibm-i',
  name: 'IBM i',
  description: 'IBM i skill family with 16 visible skills, L1/L2/L3 tiering, shared-br traceability',
  chainNodes: [
    { id: 'requirement-normalizer', label: 'Requirement Normalizer', artifactType: 'requirement', isExecutionHub: false },
    { id: 'functional-spec', label: 'Functional Spec', artifactType: 'functional-spec', isExecutionHub: false },
    { id: 'technical-design', label: 'Technical Design', artifactType: 'technical-design', isExecutionHub: false },
    { id: 'program-spec', label: 'Program Spec', artifactType: 'program-spec', isExecutionHub: true },
    { id: 'file-spec', label: 'File Spec', artifactType: 'file-spec', isExecutionHub: false },
    { id: 'ut-plan', label: 'UT Plan', artifactType: 'test-plan', isExecutionHub: false },
    { id: 'test-scaffold', label: 'Test Scaffold', artifactType: 'test-scaffold', isExecutionHub: false },
    { id: 'spec-review', label: 'Spec Review', artifactType: 'review', isExecutionHub: false },
    { id: 'dds-review', label: 'DDS Review', artifactType: 'review', isExecutionHub: false },
    { id: 'code-review', label: 'Code Review', artifactType: 'review', isExecutionHub: false },
  ],
  skills: [
    { skillId: 'ibm-i-requirement-normalizer', label: 'Requirement Normalizer', triggerPoint: 'raw-input' },
    { skillId: 'ibm-i-program-analyzer', label: 'Program Analyzer', triggerPoint: 'existing-source' },
    { skillId: 'ibm-i-impact-analyzer', label: 'Impact Analyzer', triggerPoint: 'program-analysis' },
    { skillId: 'ibm-i-functional-spec', label: 'Functional Spec Generator', triggerPoint: 'requirement-normalizer' },
    { skillId: 'ibm-i-technical-design', label: 'Technical Design Generator', triggerPoint: 'functional-spec' },
    { skillId: 'ibm-i-program-spec', label: 'Program Spec Generator', triggerPoint: 'technical-design' },
    { skillId: 'ibm-i-file-spec', label: 'File Spec Generator', triggerPoint: 'technical-design' },
    { skillId: 'ibm-i-code-generator', label: 'Code Generator', triggerPoint: 'program-spec' },
    { skillId: 'ibm-i-dds-generator', label: 'DDS Generator', triggerPoint: 'file-spec' },
    { skillId: 'ibm-i-ut-plan-generator', label: 'UT Plan Generator', triggerPoint: 'program-spec' },
    { skillId: 'ibm-i-test-scaffold', label: 'Test Scaffold Generator', triggerPoint: 'ut-plan' },
    { skillId: 'ibm-i-compile-precheck', label: 'Compile Precheck', triggerPoint: 'generated-code' },
    { skillId: 'ibm-i-spec-reviewer', label: 'Spec Reviewer', triggerPoint: 'functional-spec' },
    { skillId: 'ibm-i-document-quality-gate', label: 'Document Quality Gate', triggerPoint: 'sdd-document' },
    { skillId: 'ibm-i-dds-reviewer', label: 'DDS Reviewer', triggerPoint: 'dds-source' },
    { skillId: 'ibm-i-code-reviewer', label: 'Code Reviewer', triggerPoint: 'generated-code' },
    { skillId: 'ibm-i-workflow-orchestrator', label: 'Workflow Orchestrator', triggerPoint: 'any-stage' },
  ],
  skillDocumentContracts: [
    {
      skillId: 'ibm-i-requirement-normalizer',
      label: 'Requirement Normalizer',
      description: 'Normalizes messy Jira, email, meeting, or pasted input into a structured IBM i requirement package.',
      inputDocuments: ['raw-input'],
      outputDocuments: ['requirement-normalizer'],
      dependsOnSkills: [],
    },
    {
      skillId: 'ibm-i-program-analyzer',
      label: 'Program Analyzer',
      description: 'Analyzes existing RPGLE or CLLE source to explain current logic, call flow, and structure.',
      inputDocuments: ['existing-source'],
      outputDocuments: ['program-analysis'],
      dependsOnSkills: [],
    },
    {
      skillId: 'ibm-i-impact-analyzer',
      label: 'Impact Analyzer',
      description: 'Combines existing source understanding and a change request to identify changed behavior and risk.',
      inputDocuments: ['existing-source', 'program-analysis', 'requirement-normalizer'],
      outputDocuments: ['impact-analysis'],
      dependsOnSkills: ['ibm-i-program-analyzer', 'ibm-i-requirement-normalizer'],
    },
    {
      skillId: 'ibm-i-functional-spec',
      label: 'Functional Spec Generator',
      description: 'Produces business-functional behavior, rules, acceptance criteria, and BR continuity.',
      inputDocuments: ['requirement-normalizer', 'impact-analysis'],
      outputDocuments: ['functional-spec'],
      dependsOnSkills: ['ibm-i-requirement-normalizer'],
    },
    {
      skillId: 'ibm-i-technical-design',
      label: 'Technical Design Generator',
      description: 'Turns functional scope into module allocation, processing stages, object interaction, and impact design.',
      inputDocuments: ['functional-spec', 'impact-analysis'],
      outputDocuments: ['technical-design'],
      dependsOnSkills: ['ibm-i-functional-spec'],
    },
    {
      skillId: 'ibm-i-program-spec',
      label: 'Program Spec Generator',
      description: 'Produces implementation-ready RPGLE/CLLE logic, data contracts, and BR traceability.',
      inputDocuments: ['technical-design', 'functional-spec', 'impact-analysis'],
      outputDocuments: ['program-spec'],
      dependsOnSkills: ['ibm-i-technical-design'],
    },
    {
      skillId: 'ibm-i-file-spec',
      label: 'File Spec Generator',
      description: 'Produces PF, LF, PRTF, or DSPF file definitions with human-readable spec and machine-readable JSON.',
      inputDocuments: ['technical-design', 'functional-spec', 'impact-analysis'],
      outputDocuments: ['file-spec'],
      dependsOnSkills: ['ibm-i-technical-design'],
    },
    {
      skillId: 'ibm-i-code-generator',
      label: 'Code Generator',
      description: 'Generates RPGLE or CLLE source from Program Spec, preserving enhancement-first and format policy rules.',
      inputDocuments: ['program-spec', 'existing-source'],
      outputDocuments: ['generated-code'],
      dependsOnSkills: ['ibm-i-program-spec'],
    },
    {
      skillId: 'ibm-i-dds-generator',
      label: 'DDS Generator',
      description: 'Generates DDS source from File Spec JSON for PF, LF, PRTF, or DSPF objects.',
      inputDocuments: ['file-spec'],
      outputDocuments: ['dds-source'],
      dependsOnSkills: ['ibm-i-file-spec'],
    },
    {
      skillId: 'ibm-i-ut-plan-generator',
      label: 'UT Plan Generator',
      description: 'Produces IBM i-aware unit test plans from specs, CRs, or raw input.',
      inputDocuments: ['functional-spec', 'technical-design', 'program-spec', 'file-spec', 'raw-input'],
      outputDocuments: ['ut-plan'],
      dependsOnSkills: ['ibm-i-program-spec', 'ibm-i-file-spec'],
    },
    {
      skillId: 'ibm-i-test-scaffold',
      label: 'Test Scaffold Generator',
      description: 'Generates executable SQL/CL test scripts from a UT Plan.',
      inputDocuments: ['ut-plan'],
      outputDocuments: ['test-scaffold'],
      dependsOnSkills: ['ibm-i-ut-plan-generator'],
    },
    {
      skillId: 'ibm-i-compile-precheck',
      label: 'Compile Precheck',
      description: 'Reviews generated or written RPGLE/CLLE for compile safety before an IBM i compile.',
      inputDocuments: ['generated-code', 'existing-source'],
      outputDocuments: ['compile-precheck'],
      dependsOnSkills: ['ibm-i-code-generator'],
    },
    {
      skillId: 'ibm-i-spec-reviewer',
      label: 'Spec Reviewer',
      description: 'Reviews any spec layer for layer boundary, completeness, traceability, and downstream readiness.',
      inputDocuments: ['functional-spec', 'technical-design', 'program-spec', 'file-spec'],
      outputDocuments: ['spec-review'],
      dependsOnSkills: ['ibm-i-functional-spec', 'ibm-i-technical-design', 'ibm-i-program-spec', 'ibm-i-file-spec'],
    },
    {
      skillId: 'ibm-i-document-quality-gate',
      label: 'Document Quality Gate',
      description: 'Scores SDD documents from 0-100 and blocks downstream approval when the score is below 80.',
      inputDocuments: ['requirement-normalizer', 'functional-spec', 'technical-design', 'program-spec', 'file-spec', 'ut-plan'],
      outputDocuments: ['quality-gate'],
      dependsOnSkills: ['ibm-i-functional-spec', 'ibm-i-technical-design'],
    },
    {
      skillId: 'ibm-i-dds-reviewer',
      label: 'DDS Reviewer',
      description: 'Reviews DDS source against File Spec for syntax, completeness, and type-specific correctness.',
      inputDocuments: ['file-spec', 'dds-source'],
      outputDocuments: ['dds-review'],
      dependsOnSkills: ['ibm-i-file-spec', 'ibm-i-dds-generator'],
    },
    {
      skillId: 'ibm-i-code-reviewer',
      label: 'Code Reviewer',
      description: 'Reviews generated or manually written RPGLE/CLLE against Program Spec and enhancement safety rules.',
      inputDocuments: ['program-spec', 'generated-code', 'compile-precheck'],
      outputDocuments: ['code-review'],
      dependsOnSkills: ['ibm-i-program-spec', 'ibm-i-code-generator', 'ibm-i-compile-precheck'],
    },
    {
      skillId: 'ibm-i-workflow-orchestrator',
      label: 'Workflow Orchestrator',
      description: 'Routes work to the correct IBM i skill and next safe stage; it does not replace generation or review skills.',
      inputDocuments: ['raw-input', 'requirement-normalizer', 'existing-source', 'functional-spec', 'technical-design', 'program-spec', 'file-spec', 'generated-code', 'dds-source', 'ut-plan'],
      outputDocuments: ['workflow-routing'],
      dependsOnSkills: [],
    },
  ],
  skillFlowDocuments: [
    { sddType: 'raw-input', label: 'Raw Input / Jira CR', pathPattern: 'Jira, Confluence, email, upload, or pasted notes', artifactType: 'source', expectedTier: 'L1', traceabilityKey: 'SRC' },
    { sddType: 'existing-source', label: 'Existing RPGLE/CLLE Source', pathPattern: 'source/{library}/{member}.{rpgle|clle}', artifactType: 'source', expectedTier: 'L2', traceabilityKey: 'SRC-PGM' },
    { sddType: 'requirement-normalizer', label: 'Requirement Normalizer', pathPattern: 'docs/01-requirements/{br-id}-normalizer.md', artifactType: 'requirement', expectedTier: 'L1', traceabilityKey: 'BR-REQ' },
    { sddType: 'program-analysis', label: 'Program Analysis', pathPattern: 'docs/00-analysis/{program}-analysis.md', artifactType: 'analysis', expectedTier: 'L2', traceabilityKey: 'BR-PA' },
    { sddType: 'impact-analysis', label: 'Impact Analysis', pathPattern: 'docs/00-analysis/{br-id}-impact.md', artifactType: 'analysis', expectedTier: 'L2', traceabilityKey: 'BR-IA' },
    { sddType: 'functional-spec', label: 'Functional Spec', pathPattern: 'docs/02-functional-spec/{br-id}.md', artifactType: 'spec', expectedTier: 'L1', traceabilityKey: 'BR-FS' },
    { sddType: 'technical-design', label: 'Technical Design', pathPattern: 'docs/03-technical-design/{br-id}.md', artifactType: 'design', expectedTier: 'L2', traceabilityKey: 'BR-TD' },
    { sddType: 'program-spec', label: 'Program Spec', pathPattern: 'docs/04-program-spec/{program}.md', artifactType: 'spec', expectedTier: 'L2', traceabilityKey: 'BR-PS' },
    { sddType: 'file-spec', label: 'File Spec', pathPattern: 'docs/05-file-spec/{file}.md', artifactType: 'design', expectedTier: 'L2', traceabilityKey: 'BR-FILE' },
    { sddType: 'generated-code', label: 'Generated RPGLE/CLLE Source', pathPattern: 'src/{library}/{program}.{rpgle|clle}', artifactType: 'code', expectedTier: 'L3', traceabilityKey: 'BR-CODE' },
    { sddType: 'dds-source', label: 'DDS Source', pathPattern: 'src/dds/{file}.{pf|lf|prtf|dspf}', artifactType: 'code', expectedTier: 'L3', traceabilityKey: 'BR-DDS' },
    { sddType: 'ut-plan', label: 'UT Plan', pathPattern: 'docs/06-ut-plan/{program}.md', artifactType: 'test', expectedTier: 'L2', traceabilityKey: 'BR-UT' },
    { sddType: 'test-scaffold', label: 'Test Scaffold', pathPattern: 'docs/07-test-scaffold/{program}.md', artifactType: 'test', expectedTier: 'L3', traceabilityKey: 'BR-TEST' },
    { sddType: 'compile-precheck', label: 'Compile Precheck Report', pathPattern: 'docs/08-reviews/compile/{program}.md', artifactType: 'review', expectedTier: 'L3', traceabilityKey: 'BR-CP' },
    { sddType: 'quality-gate', label: 'Document Quality Gate', pathPattern: 'docs/08-reviews/quality/{br-id}.md', artifactType: 'review', expectedTier: 'L1', traceabilityKey: 'BR-QG' },
    { sddType: 'spec-review', label: 'Spec Review', pathPattern: 'docs/08-reviews/spec/{br-id}.md', artifactType: 'review', expectedTier: 'L2', traceabilityKey: 'BR-SR' },
    { sddType: 'dds-review', label: 'DDS Review', pathPattern: 'docs/08-reviews/dds/{file}.md', artifactType: 'review', expectedTier: 'L2', traceabilityKey: 'BR-DR' },
    { sddType: 'code-review', label: 'Code Review', pathPattern: 'docs/08-reviews/code/{program}.md', artifactType: 'review', expectedTier: 'L3', traceabilityKey: 'BR-CR' },
    { sddType: 'workflow-routing', label: 'Workflow Routing Decision', pathPattern: '.agent/manifests/{br-id}/workflow-routing.json', artifactType: 'manifest', expectedTier: 'L1', traceabilityKey: 'BR-WF' },
  ],
  documentDependencies: [
    { from: 'raw-input', to: 'requirement-normalizer', reason: 'Messy business input is normalized before SDD drafting.' },
    { from: 'existing-source', to: 'program-analysis', reason: 'Program analysis starts from existing RPGLE or CLLE source.' },
    { from: 'program-analysis', to: 'impact-analysis', reason: 'Impact analysis uses current-state program understanding.' },
    { from: 'requirement-normalizer', to: 'impact-analysis', reason: 'Impact analysis combines the normalized change request with current source behavior.' },
    { from: 'requirement-normalizer', to: 'functional-spec', reason: 'Functional spec starts from normalized BR scope and source references.' },
    { from: 'impact-analysis', to: 'functional-spec', reason: 'Enhancement functional scope should reflect impacted behavior and risk.' },
    { from: 'functional-spec', to: 'technical-design', reason: 'Technical design decomposes the agreed functional behavior.' },
    { from: 'impact-analysis', to: 'technical-design', reason: 'Enhancement design uses source-level impact and risk findings.' },
    { from: 'technical-design', to: 'program-spec', reason: 'Program specs depend on selected RPG/COBOL/CL implementation changes.' },
    { from: 'technical-design', to: 'file-spec', reason: 'File specs depend on DDS and data impact from the design.' },
    { from: 'program-spec', to: 'generated-code', reason: 'Code generation is spec-first and should not run directly from raw requirements.' },
    { from: 'existing-source', to: 'generated-code', reason: 'Enhancement generation preserves existing source format and change scope.' },
    { from: 'file-spec', to: 'dds-source', reason: 'DDS generation is driven by File Spec JSON.' },
    { from: 'program-spec', to: 'ut-plan', reason: 'Unit tests target the changed programs and procedures.' },
    { from: 'file-spec', to: 'ut-plan', reason: 'File changes affect test data setup and validation.' },
    { from: 'ut-plan', to: 'test-scaffold', reason: 'Test scaffold materializes the unit test plan.' },
    { from: 'generated-code', to: 'compile-precheck', reason: 'Compile precheck reviews generated or written source before compile.' },
    { from: 'functional-spec', to: 'spec-review', reason: 'Spec review validates business and functional completeness.' },
    { from: 'functional-spec', to: 'quality-gate', reason: 'Quality gate scores generated documents before approval can proceed.' },
    { from: 'technical-design', to: 'quality-gate', reason: 'Quality gate checks technical design completeness and traceability.' },
    { from: 'program-spec', to: 'quality-gate', reason: 'Quality gate blocks implementation readiness when document score is below threshold.' },
    { from: 'file-spec', to: 'quality-gate', reason: 'Quality gate checks data/file impact coverage before downstream generation.' },
    { from: 'technical-design', to: 'spec-review', reason: 'Spec review validates layer boundaries and downstream readiness.' },
    { from: 'program-spec', to: 'spec-review', reason: 'Spec review validates implementation readiness and BR continuity.' },
    { from: 'file-spec', to: 'spec-review', reason: 'Spec review validates file definition completeness and interoperability.' },
    { from: 'dds-source', to: 'dds-review', reason: 'DDS review checks generated or written DDS against File Spec.' },
    { from: 'file-spec', to: 'dds-review', reason: 'DDS review validates file-level impact and compatibility.' },
    { from: 'generated-code', to: 'code-review', reason: 'Code review validates RPGLE/CLLE implementation against Program Spec.' },
    { from: 'compile-precheck', to: 'code-review', reason: 'Code review should consider compile-safety findings.' },
    { from: 'program-spec', to: 'code-review', reason: 'Code review validates implementation against program specs.' },
  ],
  entryPaths: [
    { id: 'full-chain', label: 'Full Chain', description: 'New RPG/COBOL program or major redesign' },
    { id: 'enhancement', label: 'Enhancement', description: 'Modify existing RPG/COBOL or CL source' },
    { id: 'fast-path', label: 'Fast-Path', description: 'Small, well-understood change with limited impact' },
  ],
  documentStages: [
    { sddType: 'requirement-normalizer', label: 'Requirement Normalizer', pathPattern: 'docs/01-requirements/{br-id}-normalizer.md', artifactType: 'requirement', expectedTier: 'L1', traceabilityKey: 'BR-REQ' },
    { sddType: 'functional-spec', label: 'Functional Spec', pathPattern: 'docs/02-functional-spec/{br-id}.md', artifactType: 'spec', expectedTier: 'L1', traceabilityKey: 'BR-FS' },
    { sddType: 'technical-design', label: 'Technical Design', pathPattern: 'docs/03-technical-design/{br-id}.md', artifactType: 'design', expectedTier: 'L2', traceabilityKey: 'BR-TD' },
    { sddType: 'program-spec', label: 'Program Spec', pathPattern: 'docs/04-program-spec/{program}.md', artifactType: 'spec', expectedTier: 'L2', traceabilityKey: 'BR-PS' },
    { sddType: 'file-spec', label: 'File Spec', pathPattern: 'docs/05-file-spec/{file}.md', artifactType: 'design', expectedTier: 'L2', traceabilityKey: 'BR-FILE' },
    { sddType: 'ut-plan', label: 'UT Plan', pathPattern: 'docs/06-ut-plan/{program}.md', artifactType: 'test', expectedTier: 'L2', traceabilityKey: 'BR-UT' },
    { sddType: 'test-scaffold', label: 'Test Scaffold', pathPattern: 'docs/07-test-scaffold/{program}.md', artifactType: 'test', expectedTier: 'L3', traceabilityKey: 'BR-TEST' },
    { sddType: 'spec-review', label: 'Spec Review', pathPattern: 'docs/08-reviews/spec/{br-id}.md', artifactType: 'review', expectedTier: 'L2', traceabilityKey: 'BR-SR' },
    { sddType: 'dds-review', label: 'DDS Review', pathPattern: 'docs/08-reviews/dds/{file}.md', artifactType: 'review', expectedTier: 'L2', traceabilityKey: 'BR-DR' },
    { sddType: 'code-review', label: 'Code Review', pathPattern: 'docs/08-reviews/code/{program}.md', artifactType: 'review', expectedTier: 'L3', traceabilityKey: 'BR-CR' },
  ],
  specTiering: {
    tiers: ['L1', 'L2', 'L3'],
    defaultTier: 'L2',
  },
  usesOrchestrator: true,
  traceabilityMode: 'shared-br',
};
