import type { PipelineProfile } from '../types/requirement';

export const STANDARD_SDD_PROFILE: PipelineProfile = {
  id: 'standard-sdd',
  name: 'Standard SDD',
  description: 'Standard SDD synced from .claude/skills with 10 staged skills; Architecture and Design supporting docs stay in document flow',
  chainNodes: [
    { id: 'requirement', label: 'Requirement', artifactType: 'requirement', isExecutionHub: false },
    { id: 'user-story', label: 'User Story', artifactType: 'user-story', isExecutionHub: false },
    { id: 'spec', label: 'Spec', artifactType: 'spec', isExecutionHub: true },
    { id: 'architecture', label: 'Architecture', artifactType: 'architecture', isExecutionHub: false },
    { id: 'design', label: 'Design', artifactType: 'design', isExecutionHub: false },
    { id: 'tasks', label: 'Tasks', artifactType: 'tasks', isExecutionHub: false },
    { id: 'code', label: 'Code', artifactType: 'code', isExecutionHub: false },
    { id: 'review', label: 'Review', artifactType: 'review', isExecutionHub: false },
  ],
  skills: [
    { skillId: 'req-to-user-story', label: 'Requirement to Stories', triggerPoint: 'requirement' },
    { skillId: 'user-story-to-spec', label: 'Stories to Spec', triggerPoint: 'user-story' },
    { skillId: 'spec-to-architecture', label: 'Spec to Architecture', triggerPoint: 'spec' },
    { skillId: 'architecture-review', label: 'Architecture Review', triggerPoint: 'architecture' },
    { skillId: 'architecture-to-design', label: 'Architecture to Design', triggerPoint: 'architecture' },
    { skillId: 'design-to-tasks', label: 'Design to Tasks', triggerPoint: 'design' },
    { skillId: 'tasks-to-code', label: 'Tasks to Code', triggerPoint: 'tasks' },
    { skillId: 'tasks-to-implementation', label: 'Tasks to Implementation', triggerPoint: 'tasks' },
    { skillId: 'review-code-against-design', label: 'Code vs Design Review', triggerPoint: 'code' },
    { skillId: 'review-doc-quality', label: 'Document Quality Review', triggerPoint: 'sdd-document' },
  ],
  skillDocumentContracts: [
    {
      skillId: 'req-to-user-story',
      label: 'Requirement to Stories',
      description: 'Derives Jira-ready user stories from the normalized requirement document.',
      inputDocuments: ['requirement'],
      outputDocuments: ['user-story'],
      dependsOnSkills: [],
    },
    {
      skillId: 'user-story-to-spec',
      label: 'Stories to Spec',
      description: 'Generates the functional SDD spec after user stories are available.',
      inputDocuments: ['requirement', 'user-story'],
      outputDocuments: ['spec'],
      dependsOnSkills: ['req-to-user-story'],
    },
    {
      skillId: 'spec-to-architecture',
      label: 'Spec to Architecture',
      description: 'Creates the system architecture and companion Data Flow document from the spec.',
      inputDocuments: ['spec'],
      outputDocuments: ['architecture', 'data-flow'],
      dependsOnSkills: ['user-story-to-spec'],
    },
    {
      skillId: 'architecture-review',
      label: 'Architecture Review',
      description: 'Reviews architecture for extensibility, coupling, layering, and API boundary health.',
      inputDocuments: ['spec', 'architecture', 'data-flow'],
      outputDocuments: ['architecture-review'],
      dependsOnSkills: ['spec-to-architecture'],
    },
    {
      skillId: 'architecture-to-design',
      label: 'Architecture to Design',
      description: 'Generates the design artifact set, including Data Model and API Implementation Guide when applicable.',
      inputDocuments: ['spec', 'architecture', 'data-flow', 'architecture-review'],
      outputDocuments: ['design', 'data-model', 'api-guide'],
      dependsOnSkills: ['spec-to-architecture'],
    },
    {
      skillId: 'design-to-tasks',
      label: 'Design to Tasks',
      description: 'Turns the detailed design and supporting contracts into an engineering task breakdown.',
      inputDocuments: ['design', 'data-model', 'api-guide'],
      outputDocuments: ['tasks'],
      dependsOnSkills: ['architecture-to-design'],
    },
    {
      skillId: 'tasks-to-code',
      label: 'Tasks to Code',
      description: 'Implements incremental brownfield code changes from tasks.md in the current repository.',
      inputDocuments: ['tasks', 'design', 'api-guide'],
      outputDocuments: ['code', 'tests'],
      dependsOnSkills: ['design-to-tasks'],
    },
    {
      skillId: 'tasks-to-implementation',
      label: 'Tasks to Implementation',
      description: 'Handles greenfield, brownfield, or migration implementation when the repo mode must be determined first.',
      inputDocuments: ['tasks', 'design', 'architecture'],
      outputDocuments: ['implementation'],
      dependsOnSkills: ['design-to-tasks'],
    },
    {
      skillId: 'review-code-against-design',
      label: 'Code vs Design Review',
      description: 'Reviews code or PR output against design.md and tasks.md before merge or handoff.',
      inputDocuments: ['design', 'tasks', 'code', 'implementation'],
      outputDocuments: ['code-review'],
      dependsOnSkills: ['tasks-to-code', 'tasks-to-implementation'],
    },
    {
      skillId: 'review-doc-quality',
      label: 'Document Quality Review',
      description: 'Reviews SDLC documents for completeness, coherence, traceability, and readiness to move downstream.',
      inputDocuments: ['user-story', 'spec', 'architecture', 'data-flow', 'data-model', 'design', 'api-guide', 'tasks'],
      outputDocuments: ['doc-quality-review'],
      dependsOnSkills: ['user-story-to-spec', 'spec-to-architecture', 'architecture-to-design', 'design-to-tasks'],
    },
  ],
  skillFlowDocuments: [
    { sddType: 'requirement', label: 'Requirement', pathPattern: 'docs/01-requirements/{slug}-requirements.md', artifactType: 'requirement', traceabilityKey: 'REQ' },
    { sddType: 'user-story', label: 'User Stories', pathPattern: 'docs/02-user-stories/{slug}-stories.md', artifactType: 'user-story', traceabilityKey: 'US' },
    { sddType: 'spec', label: 'Spec', pathPattern: 'docs/03-spec/{slug}-spec.md', artifactType: 'spec', traceabilityKey: 'SPEC' },
    { sddType: 'architecture', label: 'Architecture', pathPattern: 'docs/04-architecture/{slug}-architecture.md', artifactType: 'architecture', traceabilityKey: 'ARCH' },
    { sddType: 'data-flow', label: 'Data Flow', pathPattern: 'docs/04-architecture/{slug}-data-flow.md', artifactType: 'architecture-support', traceabilityKey: 'FLOW' },
    { sddType: 'architecture-review', label: 'Architecture Review', pathPattern: 'docs/08-reviews/architecture/{slug}.md', artifactType: 'review', traceabilityKey: 'ARCH-REV' },
    { sddType: 'design', label: 'Design', pathPattern: 'docs/05-design/{slug}-design.md', artifactType: 'design', traceabilityKey: 'DESIGN' },
    { sddType: 'data-model', label: 'Data Model', pathPattern: 'docs/04-architecture/{slug}-data-model.md', artifactType: 'architecture-support', traceabilityKey: 'MODEL' },
    { sddType: 'api-guide', label: 'API Implementation Guide', pathPattern: 'docs/05-design/contracts/{slug}-API_IMPLEMENTATION_GUIDE.md', artifactType: 'design-support', traceabilityKey: 'API' },
    { sddType: 'tasks', label: 'Tasks', pathPattern: 'docs/06-tasks/{slug}-tasks.md', artifactType: 'tasks', traceabilityKey: 'TASK' },
    { sddType: 'code', label: 'Code Changes', pathPattern: 'Pull request diff or local repository changes', artifactType: 'code', traceabilityKey: 'CODE' },
    { sddType: 'tests', label: 'Tests', pathPattern: 'Repository test files and validation output', artifactType: 'test', traceabilityKey: 'TEST' },
    { sddType: 'implementation', label: 'Implementation', pathPattern: 'Repository implementation increment or migration output', artifactType: 'code', traceabilityKey: 'IMPL' },
    { sddType: 'code-review', label: 'Code vs Design Review', pathPattern: 'docs/08-reviews/code/{slug}.md', artifactType: 'review', traceabilityKey: 'CODE-REV' },
    { sddType: 'doc-quality-review', label: 'Document Quality Review', pathPattern: 'docs/08-reviews/doc-quality/{slug}.md', artifactType: 'review', traceabilityKey: 'DOC-REV' },
  ],
  documentDependencies: [
    { from: 'requirement', to: 'user-story', reason: 'Stories are derived from the approved requirement scope.' },
    { from: 'user-story', to: 'spec', reason: 'Spec generation needs story-level behavior and acceptance criteria.' },
    { from: 'spec', to: 'architecture', reason: 'Architecture validates the functional boundary and major components.' },
    { from: 'architecture', to: 'data-flow', reason: 'Data flow follows the architecture integration points.' },
    { from: 'architecture', to: 'architecture-review', reason: 'Architecture review checks extensibility and decoupling before design handoff.' },
    { from: 'data-flow', to: 'architecture-review', reason: 'Architecture review uses runtime flow evidence, not architecture prose alone.' },
    { from: 'architecture', to: 'design', reason: 'Design elaborates architecture decisions into implementation-facing detail.' },
    { from: 'data-flow', to: 'design', reason: 'Design depends on runtime flows and state transitions.' },
    { from: 'architecture-review', to: 'design', reason: 'Review findings should be resolved or acknowledged before detailed design.' },
    { from: 'architecture', to: 'data-model', reason: 'Data model follows persistence and domain boundaries from architecture.' },
    { from: 'design', to: 'api-guide', reason: 'API guide is generated from design contracts.' },
    { from: 'data-model', to: 'api-guide', reason: 'API payloads and states depend on the domain data model.' },
    { from: 'design', to: 'tasks', reason: 'Implementation tasks are decomposed from the design.' },
    { from: 'data-model', to: 'tasks', reason: 'Tasks need explicit data impact when persistence is in scope.' },
    { from: 'api-guide', to: 'tasks', reason: 'Tasks need endpoint and integration contracts when APIs are in scope.' },
    { from: 'tasks', to: 'code', reason: 'Brownfield implementation should be driven by a task breakdown.' },
    { from: 'code', to: 'tests', reason: 'Implemented code must be validated with repository tests.' },
    { from: 'tasks', to: 'implementation', reason: 'Greenfield or migration work starts from task intent and implementation mode.' },
    { from: 'design', to: 'code-review', reason: 'Code review compares implementation against the intended design.' },
    { from: 'tasks', to: 'code-review', reason: 'Code review checks coverage against the planned task breakdown.' },
    { from: 'code', to: 'code-review', reason: 'Review inspects the actual code changes or PR diff.' },
    { from: 'implementation', to: 'code-review', reason: 'Implementation output should be checked before merge or handoff.' },
    { from: 'user-story', to: 'doc-quality-review', reason: 'Document quality review can gate transition from stories to spec.' },
    { from: 'spec', to: 'doc-quality-review', reason: 'Document quality review can gate transition from spec to architecture.' },
    { from: 'architecture', to: 'doc-quality-review', reason: 'Document quality review can gate transition from architecture to design.' },
    { from: 'design', to: 'doc-quality-review', reason: 'Document quality review can gate transition from design to tasks.' },
    { from: 'tasks', to: 'doc-quality-review', reason: 'Document quality review can gate transition from tasks to implementation.' },
  ],
  entryPaths: [
    { id: 'standard', label: 'Standard', description: 'Single entry path through requirement capture' },
  ],
  documentStages: [
    { sddType: 'requirement', label: 'Requirement', pathPattern: 'docs/01-requirements/{slug}-requirements.md', artifactType: 'requirement', traceabilityKey: 'REQ' },
    { sddType: 'user-story', label: 'User Stories', pathPattern: 'docs/02-user-stories/{slug}-stories.md', artifactType: 'user-story', traceabilityKey: 'US' },
    { sddType: 'spec', label: 'Spec', pathPattern: 'docs/03-spec/{slug}-spec.md', artifactType: 'spec', traceabilityKey: 'SPEC' },
    { sddType: 'architecture', label: 'Architecture', pathPattern: 'docs/04-architecture/{slug}-architecture.md', artifactType: 'architecture', traceabilityKey: 'ARCH' },
    { sddType: 'data-flow', label: 'Data Flow', pathPattern: 'docs/04-architecture/{slug}-data-flow.md', artifactType: 'architecture-support', traceabilityKey: 'FLOW' },
    { sddType: 'data-model', label: 'Data Model', pathPattern: 'docs/04-architecture/{slug}-data-model.md', artifactType: 'architecture-support', traceabilityKey: 'MODEL' },
    { sddType: 'design', label: 'Design', pathPattern: 'docs/05-design/{slug}-design.md', artifactType: 'design', traceabilityKey: 'DESIGN' },
    { sddType: 'api-guide', label: 'API Implementation Guide', pathPattern: 'docs/05-design/contracts/{slug}-API_IMPLEMENTATION_GUIDE.md', artifactType: 'design-support', traceabilityKey: 'API' },
    { sddType: 'tasks', label: 'Tasks', pathPattern: 'docs/06-tasks/{slug}-tasks.md', artifactType: 'tasks', traceabilityKey: 'TASK' },
  ],
  specTiering: null,
  usesOrchestrator: false,
  traceabilityMode: 'per-layer',
};
