import type { PipelineProfile } from '../types/requirement';

export const STANDARD_SDD_PROFILE: PipelineProfile = {
  id: 'standard-sdd',
  name: 'Standard SDD',
  description: 'Spec-Driven Development pipeline with 11-node chain, 2 skills, per-layer traceability',
  chainNodes: [
    { id: 'req', label: 'Requirement', artifactType: 'requirement', isExecutionHub: false },
    { id: 'story', label: 'User Story', artifactType: 'user-story', isExecutionHub: false },
    { id: 'spec', label: 'Spec', artifactType: 'spec', isExecutionHub: true },
    { id: 'arch', label: 'Architecture', artifactType: 'architecture', isExecutionHub: false },
    { id: 'data-flow', label: 'Data Flow', artifactType: 'design', isExecutionHub: false },
    { id: 'data-model', label: 'Data Model', artifactType: 'design', isExecutionHub: false },
    { id: 'design', label: 'Design', artifactType: 'design', isExecutionHub: false },
    { id: 'api', label: 'API Guide', artifactType: 'design', isExecutionHub: false },
    { id: 'tasks', label: 'Tasks', artifactType: 'tasks', isExecutionHub: false },
    { id: 'code', label: 'Code', artifactType: 'code', isExecutionHub: false },
    { id: 'test', label: 'Test', artifactType: 'test', isExecutionHub: false },
  ],
  skills: [
    { skillId: 'req-to-user-story', label: 'CLI Story Derivation', triggerPoint: 'requirement' },
    { skillId: 'user-story-to-spec', label: 'CLI Spec Generation', triggerPoint: 'user-story' },
    { skillId: 'document-quality-gate', label: 'Document Quality Gate', triggerPoint: 'sdd-document' },
  ],
  skillDocumentContracts: [
    {
      skillId: 'req-to-user-story',
      label: 'CLI Story Derivation',
      description: 'Derives Jira-ready user stories from the normalized requirement document.',
      inputDocuments: ['requirement'],
      outputDocuments: ['user-story'],
      dependsOnSkills: [],
    },
    {
      skillId: 'user-story-to-spec',
      label: 'CLI Spec Generation',
      description: 'Generates the functional SDD spec after user stories are available.',
      inputDocuments: ['requirement', 'user-story'],
      outputDocuments: ['spec'],
      dependsOnSkills: ['req-to-user-story'],
    },
    {
      skillId: 'document-quality-gate',
      label: 'Document Quality Gate',
      description: 'Scores SDD documents from 0-100 and blocks downstream approval when the score is below 80.',
      inputDocuments: ['requirement', 'user-story', 'spec', 'architecture', 'design', 'api-guide', 'tasks'],
      outputDocuments: ['quality-gate'],
      dependsOnSkills: ['user-story-to-spec'],
    },
  ],
  documentDependencies: [
    { from: 'requirement', to: 'user-story', reason: 'Stories are derived from the approved requirement scope.' },
    { from: 'user-story', to: 'spec', reason: 'Spec generation needs story-level behavior and acceptance criteria.' },
    { from: 'spec', to: 'architecture', reason: 'Architecture validates the functional boundary and major components.' },
    { from: 'spec', to: 'quality-gate', reason: 'Quality gate scores the spec before downstream architecture and design approval.' },
    { from: 'architecture', to: 'quality-gate', reason: 'Quality gate checks architectural completeness and traceability.' },
    { from: 'design', to: 'quality-gate', reason: 'Quality gate blocks implementation readiness when design score is below threshold.' },
    { from: 'architecture', to: 'data-flow', reason: 'Data flow follows the architecture integration points.' },
    { from: 'architecture', to: 'data-model', reason: 'Data model follows the architecture persistence and interface decisions.' },
    { from: 'spec', to: 'design', reason: 'Design elaborates the approved functional spec.' },
    { from: 'design', to: 'api-guide', reason: 'API guide is generated from design contracts.' },
    { from: 'design', to: 'tasks', reason: 'Implementation tasks are decomposed from the design.' },
  ],
  entryPaths: [
    { id: 'standard', label: 'Standard', description: 'Single entry path through requirement capture' },
  ],
  documentStages: [
    { sddType: 'requirement', label: 'Requirement', pathPattern: 'docs/01-requirements/{slug}.md', artifactType: 'requirement', traceabilityKey: 'REQ' },
    { sddType: 'user-story', label: 'User Stories', pathPattern: 'docs/02-user-stories/{slug}.md', artifactType: 'user-story', traceabilityKey: 'US' },
    { sddType: 'spec', label: 'Spec', pathPattern: 'docs/03-spec/{slug}.md', artifactType: 'spec', traceabilityKey: 'SPEC' },
    { sddType: 'architecture', label: 'Architecture', pathPattern: 'docs/04-architecture/{slug}.md', artifactType: 'architecture', traceabilityKey: 'ARCH' },
    { sddType: 'data-flow', label: 'Data Flow', pathPattern: 'docs/04-architecture/{slug}-data-flow.md', artifactType: 'design', traceabilityKey: 'FLOW' },
    { sddType: 'data-model', label: 'Data Model', pathPattern: 'docs/04-architecture/{slug}-data-model.md', artifactType: 'design', traceabilityKey: 'MODEL' },
    { sddType: 'design', label: 'Design', pathPattern: 'docs/05-design/{slug}.md', artifactType: 'design', traceabilityKey: 'DESIGN' },
    { sddType: 'api-guide', label: 'API Guide', pathPattern: 'docs/05-design/contracts/{slug}-api.md', artifactType: 'design', traceabilityKey: 'API' },
    { sddType: 'tasks', label: 'Tasks', pathPattern: 'docs/06-tasks/{slug}-tasks.md', artifactType: 'tasks', traceabilityKey: 'TASK' },
    { sddType: 'quality-gate', label: 'Document Quality Gate', pathPattern: 'docs/08-reviews/quality/{slug}.md', artifactType: 'review', traceabilityKey: 'QG' },
  ],
  specTiering: null,
  usesOrchestrator: false,
  traceabilityMode: 'per-layer',
};
