-- MTF-1: Workspace key alias table supports 30-day redirect after a workspace rename.

CREATE TABLE platform_workspace_key_alias (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(64)              NOT NULL,
    former_key   VARCHAR(128)             NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_platform_workspace_key_alias UNIQUE (former_key),
    CONSTRAINT fk_platform_workspace_key_alias
        FOREIGN KEY (workspace_id) REFERENCES PLATFORM_WORKSPACE(id)
);

CREATE INDEX idx_pwa_expires ON platform_workspace_key_alias(expires_at);
