CREATE TABLE workspace_context (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_name    VARCHAR(255) NOT NULL,
    application_name  VARCHAR(255) NOT NULL,
    snow_group        VARCHAR(255),
    project_name      VARCHAR(255),
    environment_name  VARCHAR(255)
);
