CREATE TABLE test_run (
    id VARCHAR(64) PRIMARY KEY,
    workspace_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NOT NULL,
    plan_id VARCHAR(64) NOT NULL,
    environment_id VARCHAR(64) NOT NULL,
    state VARCHAR(32) NOT NULL,
    trigger_source VARCHAR(32) NOT NULL,
    actor_member_id VARCHAR(64) NOT NULL,
    external_run_id VARCHAR(128),
    duration_sec INT,
    pass_count INT NOT NULL,
    fail_count INT NOT NULL,
    skip_count INT NOT NULL,
    error_count INT NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_test_run_plan FOREIGN KEY (plan_id) REFERENCES test_plan (id),
    CONSTRAINT fk_test_run_environment FOREIGN KEY (environment_id) REFERENCES test_environment (id)
);

CREATE TABLE test_case_result (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    case_id VARCHAR(64) NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    duration_sec INT,
    last_passed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_case_result_run FOREIGN KEY (run_id) REFERENCES test_run (id),
    CONSTRAINT fk_test_case_result_case FOREIGN KEY (case_id) REFERENCES test_case (id)
);

CREATE TABLE test_failure_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id VARCHAR(64) NOT NULL UNIQUE,
    failure_excerpt CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_failure_summary_result FOREIGN KEY (result_id) REFERENCES test_case_result (id)
);

CREATE INDEX idx_test_run_plan_started ON test_run (plan_id, started_at DESC);
CREATE INDEX idx_test_case_result_case_run ON test_case_result (case_id, run_id);
CREATE INDEX idx_test_case_result_run_outcome ON test_case_result (run_id, outcome);
