CREATE TABLE test_case_req_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id VARCHAR(64) NOT NULL,
    req_id VARCHAR(32) NOT NULL,
    link_status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_case_req_link_case FOREIGN KEY (case_id) REFERENCES test_case (id)
);

CREATE TABLE testing_management_change_log (
    id VARCHAR(64) PRIMARY KEY,
    workspace_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NOT NULL,
    entry_type VARCHAR(64) NOT NULL,
    reference_id VARCHAR(64) NOT NULL,
    actor_member_id VARCHAR(64),
    payload_json CLOB,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_test_case_req_link_req ON test_case_req_link (req_id);
CREATE INDEX idx_test_case_req_link_case ON test_case_req_link (case_id);
CREATE INDEX idx_test_case_req_link_status ON test_case_req_link (link_status);
