ALTER TABLE PLATFORM_APPLICATION ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_APPLICATION ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_APPLICATION ADD rev BIGINT;

ALTER TABLE PLATFORM_SNOW_GROUP ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_SNOW_GROUP ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_SNOW_GROUP ADD rev BIGINT;

ALTER TABLE PLATFORM_WORKSPACE ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_WORKSPACE ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_WORKSPACE ADD rev BIGINT;

ALTER TABLE PLATFORM_TEMPLATE ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_TEMPLATE ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_TEMPLATE ADD rev BIGINT;

ALTER TABLE PLATFORM_CONFIGURATION ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_CONFIGURATION ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_CONFIGURATION ADD rev BIGINT;

ALTER TABLE PLATFORM_AUDIT ADD tenant_id VARCHAR(64);

ALTER TABLE PLATFORM_USER ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_USER ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_USER ADD rev BIGINT;

ALTER TABLE PLATFORM_ROLE_ASSIGNMENT ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_ROLE_ASSIGNMENT ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_ROLE_ASSIGNMENT ADD rev BIGINT;

ALTER TABLE PLATFORM_POLICY ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_POLICY ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_POLICY ADD rev BIGINT;

ALTER TABLE PLATFORM_CONNECTION ADD deleted_at TIMESTAMP;
ALTER TABLE PLATFORM_CONNECTION ADD tenant_id VARCHAR(64);
ALTER TABLE PLATFORM_CONNECTION ADD rev BIGINT;
